### ISSUE TITLE
Can't start the server anymore. 

### ISSUE THREAD

**Issue by Kastiel-Myraziel** [Ishigh1/AdvancedSeedGen#12]
Hello, 

First thanks for your amazing mod, it hyped my community to restart playing terraria on an XXL MAP ( 22000  x 6000 ). 
We have lot of players but since 2 days i can't start the server anymore... 

Since the update everytime i try to start my server it says.  

" An error occured while loading AdvancedWorldGen v2.8.12.3 
It has been decteced that this mod was built for tModLoader v2022.10.18.0 
However, you are using tModLoader v2022.9.47.9 "

Well i'm downloading the lattest release on  : <https://github.com/tModLoader/tModLoader/releases>

But still the problem is here ... Any help is welcome.

**Comment by Ishigh1** [comment]
Well the thing is, the release available in the downloads is largely outdated, the latest version is on Steam
