### ISSUE TITLE
[1.4 alpha] crash during mushroom patch stage of betterworldgen with oversized worlds

### ISSUE THREAD

**Issue by esotericist** [Ishigh1/AdvancedSeedGen#4]
in the 1.4 alpha, tried making a custom world 16800x3200 (also tried 16800x4800 to match normal world aspect ratio, and 12600x3200 to be less oversized).

consistently crashes at the point covered in the attached log.

[client.log](https://github.com/Ishigh1/AdvancedWorldGen/files/7159289/client.log)

the only mod i have that should be interacting with content at all is amulet of many minions.

normal sized worlds seem to generate fine, as do custom sized worlds within the bounds of normal large worlds (i tried 7400x2100 successfully).

**Comment by Ishigh1** [comment]
Should be fixed in the latest version
